apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-kouventa-deployment
  namespace: default
  labels:
    app: backend-kouventa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-kouventa
  template:
    metadata:
      labels:
        app: backend-kouventa
    spec:
      # The 'imagePullSecrets' section has been removed
      containers:
        - name: backend-kouventa-container
          image: hakaes/f9cozoxjvpzx:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - "ALL"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-kouventa-service
  namespace: default
  labels:
    app: backend-kouventa
spec:
  type: LoadBalancer
  selector:
    app: backend-kouventa
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
